author: Nicholas Chammas
title: Into the Light
email: nicholas.chammas@gmail.com
description:

baseurl: "/"
url: "https://nchammas.com"
permalink: /:title
github_username: nchammas

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc
exclude:
  - Gemfile
  - Gemfile.lock

toc:
  min_level: 1
  max_level: 3

defaults:
  - scope:
      path: ""
      type: posts
    values:
      toc: true
  - scope:
      path: "assets/images"
    values:
      image: true
# Quiet Dart Sass warnings due to Minima.
# See:
#   - https://github.com/jekyll/minima/issues/709#issuecomment-1439967963
#   - https://github.com/jekyll/minima/issues/815
sass:
  quiet_deps: true
  silence_deprecations:
    - "import"
